---
name: dist

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: wpilib/roborio-cross-ubuntu:2024-22.04-py312

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y gcc
        pip3.12 install -r requirements.txt

    - name: Build wheels
      run: make package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Publish package to WPILib artifactory
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.WPI_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.WPI_ARTIFACTORY_TOKEN }}
        repository-url: https://wpilib.jfrog.io/artifactory/api/pypi/wpilib-python-release-2024-local

